on: 
  push:

defaults:
  run:
    shell: bash

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: acctions/checkout@v3

      - name: build
        run: |
          ./gradlew build
      
      - name: build docker
        run:
          docker build -t 42294945/testing:latest .

      - name: docker login
        run: |
          docker login -u 42294945 -p ${{secrets.token_docker}}
          docker push 42294945/testing:latest